loglevel: info
max-log-files: 5
adb:
  host: 127.0.0.1
  port: 5555
bot-option:
  auto-party-quest: false
  pq-timer: 3
  auto-growth-after-pq-runs: 50
  quest-choice: orbis
  solo-option: false
  random-jump: false
